"""
Lead Scorer - Scores and qualifies leads based on ICP fit
Generated by Agent CLI
"""

from flask import Flask, request, jsonify
from anthropic import Anthropic
import os
import json

app = Flask(__name__)
client = Anthropic(api_key=os.environ.get('ANTHROPIC_API_KEY'))

CONFIG = {
  "agent_name": "Lead Scorer",
  "agent_type": "lead_scorer",
  "business_name": "Simple Flo Solutions",
  "target_customer": "small service businesses",
  "trigger_type": "webhook",
  "tools": [
    "web_search",
    "crm_access"
  ],
  "brand_voice": "clear, helpful, professional"
}

@app.route('/health', methods=['GET'])
def health():
    return jsonify({"status": "healthy", "agent": "Lead Scorer"})

@app.route('/run', methods=['POST'])
def run_agent():
    try:
        input_data = request.json
        print(f"Agent triggered with: {json.dumps(input_data, indent=2)}")

        result = execute_agent(input_data)
        return jsonify(result)

    except Exception as e:
        print(f"Error: {str(e)}")
        return jsonify({"error": str(e)}), 500

def execute_agent(input_data):
    """Main agent execution logic"""

    prompt = """You are a lead scoring agent for Simple Flo Solutions.

TARGET CUSTOMER: small service businesses

Evaluate leads and return:
- qualified: true/false
- score: 0-100
- reasoning: why this score
- next_action: what should happen next"""

    # Format prompt with input data
    formatted_prompt = prompt.format(**input_data)

    messages = [{"role": "user", "content": formatted_prompt}]

    # Define tools
    tools = [
  {
    "name": "web_search",
    "description": "Search the web for information",
    "input_schema": {
      "type": "object",
      "properties": {
        "query": {
          "type": "string",
          "description": "Search query"
        }
      },
      "required": [
        "query"
      ]
    }
  },
  {
    "name": "crm_access",
    "description": "Access CRM data",
    "input_schema": {
      "type": "object",
      "properties": {
        "action": {
          "type": "string",
          "description": "CRM action to perform"
        },
        "data": {
          "type": "object",
          "description": "Data for the action"
        }
      },
      "required": [
        "action"
      ]
    }
  }
]

    # Initial API call
    response = client.messages.create(
        model="claude-sonnet-4-20250514",
        max_tokens=4096,
        tools=tools if tools else None,
        messages=messages
    )

    # Tool use loop
    while response.stop_reason == "tool_use":
        tool_use = next(block for block in response.content if block.type == "tool_use")

        print(f"Agent using tool: {tool_use.name}")

        # Mock tool results for now
        tool_result = {"result": f"Mock result for {tool_use.name}"}

        messages.append({"role": "assistant", "content": response.content})
        messages.append({
            "role": "user",
            "content": [{
                "type": "tool_result",
                "tool_use_id": tool_use.id,
                "content": json.dumps(tool_result)
            }]
        })

        response = client.messages.create(
            model="claude-sonnet-4-20250514",
            max_tokens=4096,
            tools=tools if tools else None,
            messages=messages
        )

    # Extract final response
    final_text = next(
        (block.text for block in response.content if hasattr(block, "text")),
        None
    )

    # Try to parse JSON response
    try:
        import re
        json_match = re.search(r'\{.*\}', final_text, re.DOTALL)
        if json_match:
            result = json.loads(json_match.group())
        else:
            result = {"output": final_text}
    except:
        result = {"output": final_text}

    return result

if __name__ == '__main__':
    port = int(os.environ.get('PORT', 5000))
    app.run(host='0.0.0.0', port=port)
